import { generateEslintConfig } from '@companion-module/tools/eslint/config.mjs'

const baseConfig = await generateEslintConfig({
	enableTypescript: true,
	// `.remember` is regenerated by a local tooling plugin and is not part of this project;
	// `captures` holds raw device payloads pulled from a live Ecamm for fixture authoring.
	ignores: ['.remember/**', 'captures/**', 'dist/**', 'coverage/**', 'pkg/**'],
})

export default [
	...baseConfig,
	{
		// Test and tooling files legitimately import devDependencies and are never published,
		// so the "unpublished import" rule does not apply to them.
		files: ['tests/**/*.ts', 'scripts/**/*.ts', 'vitest.config.ts'],
		rules: {
			'n/no-unpublished-import': 'off',
			// The "methods" referenced here are vi.fn() mocks being asserted on, not real class
			// methods, so the unbound-this warning does not apply.
			'@typescript-eslint/unbound-method': 'off',
		},
	},
]
